package com.geektrust.backend.Constants;

public class constants {
    public static final int ZERO = 0;
    public static final int ONE = 1;
    public static final int TWO = 2;
    public static final int THREE = 3;
    public static final int FOUR = 4;
    public static final int HUNDRED = 100;
    public static final int MIN_NUMBER_DRIVERS = 5;
    public static final String RIDE_NOT_COMPLETED = "RIDE_NOT_COMPLETED";
    public static final String INVALID_RIDE =  "INVALID_RIDE";
    public static final int BASE_FARE = 50;
    public static final float PER_KILOMETER_CHARGE = 6.5f;
    public static final int CHARGE_FOR_TIME_SPENT_IN_CAR = 2;
    public static final int SERVICE_TAX = 20;
    public static final int SQUARE = 2;
    public static final String TWO_DECIMAL_LIMIT_FORMAT = "0.00";
    public static final long RANGE_OF_DISTANCE = 5;
    public static final String DRIVER_NOT_AVAILABLE = "Driver requested is not Available";
    public static final String DRIVER_NOT_FOUND = "Driver not found";
    public static final String RIDER_NOT_FOUND = "Rider not found";
    public static final String RIDE_NOT_FOUND = "Ride not found";
    public static final String TIME_CANNOT_BE_NEGATIVE = "Time duration cannot be negative";
    public static final String ADD_DRIVER = "ADD_DRIVER";
    public static final String ADD_RIDER = "ADD_RIDER";
    public static final String MATCH = "MATCH";
    public static final String START_RIDE = "START_RIDE";
    public static final String STOP_RIDE = "STOP_RIDE";
    public static final String BILL = "BILL";
    public static final String DRIVER_WITH_ID_PRESENT = "Driver with this id is already present";
    public static final String RIDER_WITH_ID_PRESENT = "Rider with this id is already present";
    public static final String DRIVERS_MATCHED = "DRIVERS_MATCHED ";
    public static final String NO_DRIVERS_AVAILABLE = "NO_DRIVERS_AVAILABLE";
    public static final String RIDE_STARTED = "RIDE_STARTED ";
    public static final String RIDE_STOPPED = "RIDE_STOPPED ";
    public static final String SINGLE_SPACE_STRING = " ";
    public static final String INPUT = "input1.txt";
    public static final String SLASH_SEPARATOR  = "/";
    public static final String DOLLAR_JOINER = "$";
}
